[project]
name = "collateral-gateway"
authors = ["Enterprise Solutions Team"]
description = "Secure document management and access control system on Stacks"
telemetry = false
requirements = []
[contracts.collateral_gateway]
path = "contracts/collateral-gateway.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
